### ISSUE TITLE
Chap 6: .format

### ISSUE THREAD

**Issue by motngaynaodo** [giangm9/son-python#7]
```python
>>> table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 7678}
>>> for name, phone in table.items():
...     print('{0:10} ==> {1:10d}'.format(name, phone))
...
Jack       ==>       4098
Dcab       ==>       7678
Sjoerd     ==>       4127
```
ở dòng 3 trong `{0:10} ==> {1:10d}`thì `10` với `10d` có nghĩa là gì
* khi thay `10` thành `20` thì ra
```python
>>> print('{0:20} ==> {1:10d}'.format(name, phone))
Dcab                 ==>       7678
```
* khi thay `10d` thành `20d` thì thành:

```python
>>> print('{0:10} ==> {1:20d}'.format(name, phone))
Dcab       ==>                 7678
```
* khi thay `10` thành `10d` thì thành:
```python
print('{0:10d} ==> {1:20d}'.format(name, phone))
Traceback (most recent call last):
  File "<pyshell#66>", line 1, in <module>
    print('{0:10d} ==> {1:20d}'.format(name, phone))
ValueError: Unknown format code 'd' for object of type 'str'
```
Như vậy thì là cách

**Comment by giangm9** [comment]
nó là độ dài của đoạn viết ra `10` tức là nếu nhỏ hơn `10` thì thêm dấu cách cho đủ 10
còn `d` là `decima`, tức là số sẽ đc viết ra ở hệ đếm cơ số  10

**Comment by motngaynaodo** [comment]
Nhưng mà khi thay `10d` thành `20d`
```python
>>> print('{0:10} ==> {1:20d}'.format(name, phone))
Dcab       ==>                 7678
```
thì thấy dấu cách nhiều hơn ở phía trước, vậy số trước chữ `d` có ý nghĩa gì trong hệ cơ số `10` mà lại thêm dấu cách?

**Comment by giangm9** [comment]
20 thì đương nhiên là dài hơn rồi, thêm dâu cách cho đủ độ dài 20 thì phải dài hơn 10 chứ
`d` để viết ra `int` hệ đếm 10, thử thay d bằng `f` sẽ thấy
